#pg.123 문제1 ~ 문제5
install.packages("ggplot2")
library(ggplot2)
midwest <- as.data.frame(ggplot2::midwest)
head(midwest)
tail(midwest)
View(midwest)
dim(midwest)
summary(midwest)
str(midwest)
install.packages("dplyr")
library(dplyr)
midwest <- rename(midwest, total = poptotal)
midwest <- rename(midwest, asian = popasian)
midwest$percentageasian <- (midwest$asian / midwest$total * 100)
hist(midwest$percentageasian)
#midwest$meanasian <- mean(midwest$asian)
#midwest$grades <- ifelse(midwest$meanasian >)
mean(midwest$percentageasian)
midwest$grades <- ifelse(midwest$percentageasian > mean(midwest$percentageasian), "large", "small")
table(midwest$grades)
qplot(midwest$grades)
